# Generated by Django 4.2.26 on 2025-11-24 23:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', '🟢 Entrada'), ('SALIDA', '🔴 Salida')], max_length=10)),
                ('cantidad', models.IntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('motivo', models.CharField(blank=True, help_text='Ej: Venta, Compra, Merma', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='movimiento',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='movimiento',
            name='usuario',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='precio_venta',
            new_name='precio',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='precio_compra',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='empresa',
        ),
        migrations.AlterField(
            model_name='producto',
            name='min_stock',
            field=models.IntegerField(default=5, verbose_name='Stock Mínimo (Alerta)'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='ubicacion',
            field=models.CharField(max_length=50, verbose_name='Ubicación en Tienda'),
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Movimiento',
        ),
        migrations.AddField(
            model_name='movimientostock',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.producto'),
        ),
        migrations.AddField(
            model_name='movimientostock',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
