# Generated by Django 4.2.10 on 2025-11-30 11:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_categoria_alter_proveedor_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proveedor',
            options={'verbose_name_plural': 'Proveedores'},
        ),
        migrations.RemoveField(
            model_name='producto',
            name='categoria',
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
        migrations.AlterField(
            model_name='movimientostock',
            name='motivo',
            field=models.CharField(blank=True, help_text='Ej: Venta, Compra, Merma', max_length=100),
        ),
        migrations.AlterField(
            model_name='movimientostock',
            name='tipo',
            field=models.CharField(choices=[('ENTRADA', '🟢 Entrada'), ('SALIDA', '🔴 Salida')], max_length=10),
        ),
        migrations.AlterField(
            model_name='movimientostock',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='producto',
            name='min_stock',
            field=models.IntegerField(default=5, verbose_name='Stock Mínimo (Alerta)'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='proveedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.proveedor'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='sku',
            field=models.CharField(max_length=50, unique=True, verbose_name='Código SKU'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='telefono',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='stock',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='core.producto'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='ubicacion',
            field=models.CharField(max_length=50, verbose_name='Ubicación en Tienda'),
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
